import { sql } from "drizzle-orm";
import { pgTable, text, varchar, integer, jsonb, timestamp, boolean, serial, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Session storage table for Replit Auth
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)],
);

// User storage table for Replit Auth
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: varchar("email").unique(),
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;

// Target companies being tracked
export const targets = pgTable("targets", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  url: text("url").notNull(),
  icon: text("icon").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertTargetSchema = createInsertSchema(targets).omit({ id: true, createdAt: true });
export type InsertTarget = z.infer<typeof insertTargetSchema>;
export type Target = typeof targets.$inferSelect;

// Analysis reports generated by Gemini
export const analysisReports = pgTable("analysis_reports", {
  id: serial("id").primaryKey(),
  url: text("url").notNull(),
  title: text("title").notNull(),
  summary: text("summary").notNull(),
  competitors: jsonb("competitors").$type<string[]>().notNull(),
  swot: jsonb("swot").$type<{
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
  }>(),
  battleCard: jsonb("battle_card").$type<{
    killPoints: string[];
    objectionHandling: string[];
  }>(),
  scenarios: jsonb("scenarios").$type<string[]>().notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertAnalysisReportSchema = createInsertSchema(analysisReports).omit({ id: true, createdAt: true });
export type InsertAnalysisReport = z.infer<typeof insertAnalysisReportSchema>;
export type AnalysisReport = typeof analysisReports.$inferSelect;

// Research sessions (chat history)
export const researchSessions = pgTable("research_sessions", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  agent: text("agent").notNull().default("Deep Research Agent"),
  messages: jsonb("messages").$type<ChatMessage[]>().notNull().default([]),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const insertResearchSessionSchema = createInsertSchema(researchSessions).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertResearchSession = z.infer<typeof insertResearchSessionSchema>;
export type ResearchSession = typeof researchSessions.$inferSelect;

// Signals detected from tracking
export const signals = pgTable("signals", {
  id: serial("id").primaryKey(),
  targetId: integer("target_id").references(() => targets.id),
  title: text("title").notNull(),
  description: text("description").notNull(),
  priority: text("priority").notNull().default("Medium"),
  source: text("source"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertSignalSchema = createInsertSchema(signals).omit({ id: true, createdAt: true });
export type InsertSignal = z.infer<typeof insertSignalSchema>;
export type Signal = typeof signals.$inferSelect;

// Frontend-only types for the application
export interface Scenario {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export interface AnalysisResult {
  summary: string;
  competitors: string[];
  swot?: {
    strengths: string[];
    weaknesses: string[];
    opportunities: string[];
    threats: string[];
  };
  battleCard?: {
    killPoints: string[];
    objectionHandling: string[];
  };
}

export enum AppState {
  IDLE = 'IDLE',
  SCENARIO_SELECTION = 'SCENARIO_SELECTION',
  ANALYZING = 'ANALYZING',
  RESULTS = 'RESULTS',
  ERROR = 'ERROR'
}

export enum WorkbenchView {
  RADAR = 'RADAR',
  TARGETS = 'TARGETS',
  RESEARCH = 'RESEARCH',
  LIBRARY = 'LIBRARY',
  ACTS_TEMPLATE = 'ACTS_TEMPLATE',
  LINK_WORKSPACE = 'LINK_WORKSPACE'
}

export interface TargetCompany {
  id: number;
  name: string;
  url: string;
  icon: string;
}

export interface ReasoningStep {
  id: string;
  desc: string;
  status: 'pending' | 'active' | 'done';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'agent';
  content: string;
  timestamp: string;
  reasoning?: ReasoningStep[];
  isThinking?: boolean;
}

// API request/response schemas
export const generateIntelligenceRequestSchema = z.object({
  url: z.string().url(),
  selectedScenarios: z.array(z.string()),
});

export type GenerateIntelligenceRequest = z.infer<typeof generateIntelligenceRequestSchema>;

export const chatRequestSchema = z.object({
  sessionId: z.number().optional(),
  message: z.string().min(1),
});

export type ChatRequest = z.infer<typeof chatRequestSchema>;
